[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "2c588c61459962055d05a37be459953b17a31674"
os = "macos"

    [[Libcerf.download]]
    sha256 = "2d7f9ffa0c0672f04f6e83bf1f743d2ce00575df1dfe29d4ecdb3513f13dd023"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.aarch64-apple-darwin.tar.gz"
[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "617f553c04d84cfae61c7596cbd0f7ffbf93b535"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "28b50574304b5e69bbed4a451f83b2bffda1a9be90a09947ad792590067e1527"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "6f0ce0da7cf3084cc71d9fb769e7aed95d67426a"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "97c3407193c991fde0b1049d681a1ef364935b05b3fb8c849370becaec121a80"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.aarch64-linux-musl.tar.gz"
[[Libcerf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "acda985d93213a24651f6ee3eeadca2381b7d6ee"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "05e690321a602a0d21187d422d579e03960643ad06f0bbe8b618b064ced77efd"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.armv6l-linux-gnueabihf.tar.gz"
[[Libcerf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d19c3a784206ccf543c07ce8dfda81f46d47e52"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "7ccbbadadfe3649f0341bb0a03cda01bf071a32328d3f5c1101760408502bc3f"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.armv6l-linux-musleabihf.tar.gz"
[[Libcerf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f14b585f2deb84ed289c609b30ec9ef507a9611"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "846f7ac3f0950e472f3d30a785a0bee2c3d8c36fbb164a61e97195f00ee0d1ee"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Libcerf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8bbd2a00b424b0d3d79b5c942cfe9959d4d6c91b"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "b074a6c072be335490ebd6a3a63cb804740e95677503adc0178edb0f1f68043c"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "8f1e5bc02fef2542cf3510ad24a453306044ede0"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "38e2a827e9ceaf0649ddf076fb7e54782fc2b8acaa6c3264b9413fb3eec19f35"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.i686-linux-gnu.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "c0fb02d6b4a4ec67c807310acaf7e402f593497f"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "3de06ee241ac95c105a026bd496467f702ad2a9a5ed97298d983b74306d6250e"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.i686-linux-musl.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "d298d7266d092e718e6aec1c4306bb3bb0c6c34f"
os = "windows"

    [[Libcerf.download]]
    sha256 = "030bfee399f62f26b7850759604ade8129b4695ce981293b4251a6c89e87135a"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.i686-w64-mingw32.tar.gz"
[[Libcerf]]
arch = "powerpc64le"
git-tree-sha1 = "6be10a376f3fd719f2064ae470a7c7569c6d49f6"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "cd58c2ab59423f61ba8d55b406663b126227c7815f02006c69f9428de225f6d6"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "f9eb9b3c05758a5ec1293142b424fa2642683955"
os = "macos"

    [[Libcerf.download]]
    sha256 = "a0f02d1541d40faddde81be1bf2adc92ff0580ce4675d5ca0b12263850768ff0"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.x86_64-apple-darwin.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "32a6de486f93527c7d223b84fcddde53bf6676e0"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "ad06828664a43c35ae83d7a77a8358edc14143566ae82651def5f75814ca534b"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "6bda13f54758121b4d89dff4aa6c35d0c9cc5540"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "9088057e172690317a44a1da19fefc913508d787a096705565b6719ddbc03af3"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.x86_64-linux-musl.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "28f2a99e4983d176a203b9e557b30534a45729c6"
os = "freebsd"

    [[Libcerf.download]]
    sha256 = "38a16873f2f0bf2040c5b11fc42ab9005de3a26883d55d420df8b19b84efeb98"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.x86_64-unknown-freebsd.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "231a53dac6fa0e5293789aac33fff0f9c0cdd033"
os = "windows"

    [[Libcerf.download]]
    sha256 = "c244feba80bb3b7a9dbcf7e6768df3959a76e635db1317bd07f300ca42bf3f85"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v1.17.0+0/Libcerf.v1.17.0.x86_64-w64-mingw32.tar.gz"
