[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "fda2b9eb2a7c644410035582b5234d55d0ad1c8f"
os = "macos"

    [[Libcerf.download]]
    sha256 = "1c03a94b50cb8556bce52293057d3667712258ec239d8dcc35dea436e37b97fa"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.aarch64-apple-darwin.tar.gz"
[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "9a491dc5e2ee6b33d79521a2d6b1819c766b843d"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "5a90d10a711fe44c19c76ba163fbf8d16046313325d8f6b44e19112c3babb837"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.aarch64-linux-gnu.tar.gz"
[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "90d97198df5971a2f5eb3817f4ad2e92c2403252"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "8661dead8840c896c6a3d7dfbddd8008c5c1ada873882e28c55e21a697b9d80c"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.aarch64-linux-musl.tar.gz"
[[Libcerf]]
arch = "aarch64"
git-tree-sha1 = "8ab9003b7ab918433f9977182708679dc85b192a"
os = "freebsd"

    [[Libcerf.download]]
    sha256 = "3be81ca07abbeb68071899f8883ca5d7bfecb73a25a7188c09ff4e70bf786ee5"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.aarch64-unknown-freebsd.tar.gz"
[[Libcerf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3504b4cc2da9f0e0042d47b7ee9a79034f694a4"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "69830db9fae2970d7802896f20052f498d6c6e0a959c625caa7cb8d406de3be0"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Libcerf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0edcc3732a4c262f5429b86b8c3d71ff07176f69"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "fecfa2013aa544d01f1cf785e407346fdce1a1666054f1bfef14a7be61b0b219"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[Libcerf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e02cc402f9351168417a71281cb60ff400ba8db"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "4c1dccd930391fcc8eeaf122f6a983d884b6085996780a278d70312337acc91c"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Libcerf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0b82151426d313b7857677460f52f10122159ff"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "077f035d5ca594b387f12f716cc82f8825e924dfabe03b9199abea68e0b30f78"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "bd001b885c15a16cd9a86c03fe937402b3c1fe7c"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "2dd3fccda63eb09f01f43404a520cdb105751c30b6f496bf1d11a6d95b1f7e00"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.i686-linux-gnu.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "dace4bbe0ac24ec5bdc5f1a6f2cc4a8f73597a87"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "401a1ff413befb2a1a716f3d117cb00db7e094e5e32b95aef72f675ed449f1c5"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.i686-linux-musl.tar.gz"
[[Libcerf]]
arch = "i686"
git-tree-sha1 = "f64e2bf895919e5b166c3f4f30e580c96c5a2d9e"
os = "windows"

    [[Libcerf.download]]
    sha256 = "1600443c065fc5f50ccad5235378d69fc387b87bba030be750d5edcd0be18564"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.i686-w64-mingw32.tar.gz"
[[Libcerf]]
arch = "powerpc64le"
git-tree-sha1 = "d45bd70eea4fa89f91a9f2e81552e52357303da2"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "274d6e86cfec3acc4d0c3721b9efffe1f4fb68e15f827369a87cd5a80b9145e5"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[Libcerf]]
arch = "riscv64"
git-tree-sha1 = "f20e759fd576c0bd797d17f64ae6e3f1edbff1a6"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "69b29b13f1c4398d7e8d65f7e2cb59fe1cd414c5ca458ca0a5716a76ac3c7ec9"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.riscv64-linux-gnu.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "5121b7e4bf69e6e05b013e123230cc25134f49d5"
os = "macos"

    [[Libcerf.download]]
    sha256 = "a154265080a1db83bfae526b0f3827983e7415b3611bb4c2ae90f99c7d94a842"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.x86_64-apple-darwin.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "a0e532a00fb3a0501d680229ecc0689e6f09005e"
libc = "glibc"
os = "linux"

    [[Libcerf.download]]
    sha256 = "46a1aaa6116e63d192f94bbe5604715baad6dad0d98e9800576e433d433c3657"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.x86_64-linux-gnu.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "be9cec1b64d7b2eda98b692c818d4be6aea311ed"
libc = "musl"
os = "linux"

    [[Libcerf.download]]
    sha256 = "c845ae37424590d3dd3393e8a1e55f9f5f6c256be1bb758f526354c938923414"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.x86_64-linux-musl.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "d37d3fe3a8f6f7c76f1a82847a3e9f01f2bba9db"
os = "freebsd"

    [[Libcerf.download]]
    sha256 = "87d44a2f2f34858e970457ebabb07faa0dbe9eb09cfa013a1711a701b75baeaf"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[Libcerf]]
arch = "x86_64"
git-tree-sha1 = "70c3926aedb19ecdddc06e96d9ea42b215556eff"
os = "windows"

    [[Libcerf.download]]
    sha256 = "0c76f79ad333779319c54353d448f04555b12db644fa5e8accd6c2b5f66c6534"
    url = "https://github.com/JuliaBinaryWrappers/Libcerf_jll.jl/releases/download/Libcerf-v2.5.0+0/Libcerf.v2.5.0.x86_64-w64-mingw32.tar.gz"
